name: Update Theses List

on:
  schedule:
    # Ogni lunedì alle 06:00 UTC (le 08:00 circa a Pisa in ora legale)
    - cron: "0 6 * * 1"
  workflow_dispatch: {}  # consente l'avvio manuale dal tab "Actions"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Scrape ETD and build JSON
        run: |
          python scripts/parse_etd.py

      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain data/theses.json)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/theses.json
            git commit -m "chore: update theses.json [skip ci]"
            git push
          else
            echo "No changes."
          fi
